accountUser/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
# from django.urls import include, url

app_name = "accountUser"
urlpatterns = [
    path('login/', LoginView.as_view(template_name='registration/signin.html'), name="signin"),
    path('logout/', LogoutView.as_view(template_name='registration/signout.html'), name="logout"),

]

adminDashboardApp/urls.py
from django.urls import path
from adminDashboardApp import views

app_name = 'adminDashboardApp'

urlpatterns = [
    path('', views.adminDashboard, name="dashboard"),
    path('pdf/', views.test, name="test"),
    path('createNewUser/', views.employeeRegisterUser, name='createNewUser'),
    path('employeePersonal/<int:pk>/', views.employeePersonalDetail,
         name='employeePersonalDetail'),
    path('listEmployee/', views.employeeDetailList, name="employee_list"),
    path('listAdmin/', views.adminDetailList, name="admin_list"),
    path('createRole/',
         views.createRoleAdmin.as_view(), name="createRole"),
    path('roleUpdate/<slug:slug>',
         views.roleUpdateView.as_view(), name="roleUpdate"),
    path('deleteRole/<slug:slug>',
         views.deleteAdminUserRoles.as_view(), name="deleteRole"),
    path('convertToAdmin/<int:pk>',
         views.convertNormalUserToAdmin, name="convertToAdmin"),
    path('convertToNormal/<int:pk>',
         views.convertAdminToNormal, name="convertToNormal"),
    path('deleteUser/<int:pk>/<str:nm>',
         views.deactivatedUserByAdmin, name="deleteUser"),
    path('deactivatedUsers/',
         views.deactivatedUsers, name="deactivatedUsers"),
    path('activatedUsers/<int:pk>',
         views.activatedUsers, name="activatedUsers"),
    path('deleteDeactivatedUser/<int:pk>',
         views.deleteDeactivatedUser.as_view(), name="deleteDeactivatedUser"),
    #path('attendance/', views.AttendanceRecord.as_view(), name="attendance"),
    path('attendance/', views.attendance, name="attendance"),
    path('joinLetter/', views.joinLetter, name="joinLetter"),
    path('converted_pdf/', views.convertPdf, name='converted_pdf'),

    path('zoom_meeting/', views.zoomMeeting, name='zoom_meeting'),
    path('zoom_meeting_create/', views.zoomMeetingCreateView.as_view(),
         name='zoom_meeting_create'),
    path('zoom_meeting_user_create/<int:pk>', views.zoomMeetingUsersCreateView.as_view(),
         name='zoom_meeting_user_create'),
    path('zoom_meeting_list/', views.zoomMeetingListView.as_view(),
         name='zoom_meeting_list'),
    path('zoom_meeting_user_details/<int:pk>', views.zoomMeetingDetailView.as_view(),
         name='zoom_meeting_user_detail'),
    path('zoom_meeting_Delete/<int:pk>', views.zoomMeetingDeleteView.as_view(),
         name='zoom_meeting_Delete'),
    path('zoom_meeting_send_mail/<int:pk>', views.zoomMeetingSendMailView.as_view(),
         name='zoom_meeting_send_mail'),
    path('organisation/', views.organisationView.as_view(),
         name='organisation_detail'),

    path('department/', views.departmentListView.as_view(),
         name="department"),
    path('departmentcreate/', views.departmentCreateView.as_view(),
         name="department_create"),
    path('departmentupdate/<int:pk>', views.departmentUpdateView.as_view(),
         name="department_update"),
    path('departmentdelete/<int:pk>', views.departmentDeleteView.as_view(),
         name="department_delete"),
]

adminDashboardPro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminDashboardApp.urls', namespace='adminDjango')),
    path('accounts/', include('accountUser.urls', namespace='account')),
    path('jobs/', include('jobPortalApp.urls', namespace='jobs')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

adminDashboardApp/forms.py
from django import forms
from django.contrib.auth.models import User
from adminDashboardApp.models import EmployeeProfile, AdminUserRoles, Department, ZoomMeetings, ZoomMeetingsUsers


class UserForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'email']


class EmployeePersonalDetailForm(forms.ModelForm):
    first_name = forms.CharField(label="First Name", widget=forms.TextInput)
    last_name = forms.CharField(label="Last Name", widget=forms.TextInput)

    class Meta:
        model = EmployeeProfile
        fields = ['first_name', 'last_name', 'age',
                  'address', 'contact_number', 'gender']


class AdminUserRolesForm(forms.ModelForm):
    class Meta:
        model = AdminUserRoles
        fields = ['user', 'roles']


class AttendanceDetailForm(forms.Form):
    file_name = forms.FileField(
        label="Upload the files", widget=forms.FileInput)
    emp_id = forms.CharField(
        label="Enter Employee's ID", widget=forms.TextInput)
    fields = ['file_name', 'emp_id']


class EmployeeDepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['company', 'department_name', 'employee']


class ZoomMeetingsForm(forms.ModelForm):
    class Meta:
        model = ZoomMeetings
        fields = ['meeting_topic', 'meeting_date',
                  'meeting_time', 'meeting_duration']


class ZoomMeetingsUsersForm(forms.ModelForm):
    class Meta:
        model = ZoomMeetingsUsers
        fields = ['zoom_meeting', 'users', 'users_staff']


class ZoomMeetingsSendMailForm(forms.ModelForm):
    class Meta:
        model = ZoomMeetingsUsers
        fields = ['message']

adminDashboardApp/views.py
from django.shortcuts import redirect, render, HttpResponse
from django.contrib.auth.models import User
from adminDashboardApp.forms import UserForm, EmployeePersonalDetailForm, \
    AdminUserRolesForm, AttendanceDetailForm, EmployeeDepartmentForm, ZoomMeetingsForm, ZoomMeetingsUsersForm, ZoomMeetingsSendMailForm
from adminDashboardApp.models import EmployeeProfile, AdminUserRoles, Company, Department, ZoomMeetings, ZoomMeetingsUsers
from django.views.generic import UpdateView, CreateView, ListView, DeleteView, DetailView

from datetime import datetime
from django.template.loader import render_to_string
from django.http import HttpResponse
import weasyprint
from weasyprint import HTML, CSS
import os
import io
from django.views.generic.edit import FormView
from django.conf import settings
import jwt
import requests
import json
from time import time
from .utills import createMeeting
from django.core.mail import send_mail


def test(request):
    this_folder = os.path.dirname(os.path.abspath(__file__))
    context = {
        'emp_name': "hello",
        'date': "12-2-2002",
        'position': 'Hr',
        'location': "kolkata",
        'pre_company': "webkrone",
        'guardian': "ghhgd",
        'image_path':  'file://' + os.path.join(this_folder, 'static', 'images', 'webkrone.png')
    }
    return render(request, 'joiningLetter/pdf_change.html', context)


def adminDashboard(request):
    return render(request, 'dashboard/dashboard.html')


def employeeDetailList(request):
    employees = EmployeeProfile.objects.filter(
        user__is_staff=False, user__is_active=True)
    return render(request, 'Employee/display_user.html', {'employees': employees,
                                                          'admin': False})


def adminDetailList(request):
    employees = EmployeeProfile.objects.filter(
        user__is_staff=True, user__is_active=True)
    return render(request, 'Employee/display_user.html', {'employees': employees,
                                                          'admin': True})


def employeeRegisterUser(request):
    """
        Employee can register new admin users.
    """

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the choosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return redirect('adminDashboardApp:employeePersonalDetail',
                            pk=new_user.id)

    else:
        user_form = UserForm()
        return render(request, 'Employee/create_user.html',
                      {'user_form': user_form})


def employeePersonalDetail(request, pk):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        age = request.POST['age']
        gender = request.POST['gender']
        contact = request.POST['contact_number']
        address = request.POST['address']

        user = User.objects.get(id=pk)
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        employee = EmployeeProfile()
        employee.age = age
        employee.gender = gender
        employee.user = user
        employee.contact_number = contact
        employee.address = address
        employee.save()
        return redirect('adminDashboardApp:dashboard')
    else:
        personal_form = EmployeePersonalDetailForm()
        return render(request, 'Employee/personal_detail.html',
                      {'personal_form': personal_form})


class createRoleAdmin(CreateView):
    """
        Admin user can add the roles to particular admin users.
    """
    form_class = AdminUserRolesForm
    template_name = 'roles/create_role_admin_user.html'

    def form_valid(self, form):
        data = form.save(commit=False)
        user = self.request.POST['user']
        user = User.objects.get(id=user)
        data.user = user
        data.save()
        return redirect('adminDashboardApp:createRole')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['roles'] = AdminUserRoles.objects.all()
        return context


class roleUpdateView(UpdateView):
    """
        Admin users can update the roles of other admin users.
    """
    model = AdminUserRoles
    form_class = AdminUserRolesForm
    template_name = 'roles/edit_role_admin_user.html'
    success_url = '/createRole/'

    def get_form_kwargs(self):
        kwargs = super(roleUpdateView, self).get_form_kwargs()
        kwargs.update()
        return kwargs


class deleteAdminUserRoles(DeleteView):
    """
        Admin users can delete the roles of admin users.
    """
    model = AdminUserRoles
    template_name = 'roles/delete_role_admin_user.html'
    success_url = '/createRole/'


def convertNormalUserToAdmin(request, pk):
    """
        Admin users can make admin user from normal user.
    """
    if request.user.is_staff == True:
        user = User.objects.get(id=pk)
        user.is_staff = True
        user.save()
        return redirect('adminDjango:employee_list')


def convertAdminToNormal(request, pk):
    """
        Admin users can make admin user from normal user.
    """
    if request.user.is_staff == True:
        user = User.objects.get(id=pk)
        user.is_staff = False
        user.save()
        return redirect('adminDjango:admin_list')


def deactivatedUserByAdmin(request, pk, nm):
    """
        Admin users can make admin user from normal user.
    """
    if request.user.is_staff == True:
        user = User.objects.get(id=pk)
        if nm == "deactivate":
            user.is_staff = False
            user.is_active = False
        user.save()
        return redirect('adminDjango:admin_list')


def deactivatedUsers(request):
    employees = EmployeeProfile.objects.filter(user__is_active=False)
    return render(request, 'Employee/display_user.html', {'employees': employees,
                                                          'admin': True})


def activatedUsers(request, pk):
    """
        Admin users can make admin user from normal user.
    """
    if request.user.is_staff == True:
        user = User.objects.get(id=pk)
        user.is_staff = False
        user.is_active = True
        user.save()
        return redirect('adminDjango:deactivatedUsers')


class deleteDeactivatedUser(DeleteView):
    """
        Admin users can delete the roles of admin users.
    """
    model = User
    template_name = 'Employee/delete_user.html'
    success_url = '/deactivatedUsers/'


def attendance(request):
    if request.method == 'POST':

        id = request.POST['id']
        try:
            file_name = request.FILES['datafile']
            file = file_name.readlines()
        except:
            return render(request, 'attendanceRecord/attendance.html')

        result = []
        for item in file:
            data = {}
            all_data = (str(item)).replace("b\'", '')
            all_data = all_data.replace('\\t', ' ')
            all_data = all_data.replace('\\r', '')
            all_data = all_data.replace('\\n', '')
            all_data = (str(all_data)).split(' ')
            lst = []
            for i in all_data:
                if i != "":
                    lst.append(i)

            all_data = lst
            all_data[2] = datetime.strptime(all_data[2], '%H:%M:%S')

            value = 0
            for item in result:
                if all_data[0] == item['id'] and all_data[1] == item['date']:
                    if all_data[2]:
                        item['checkout'] = all_data[2]
                        if 'checkin' in item:
                            item['duration'] = item['checkout']-item['checkin']
                    value = 1
                    break
            if value == 0:
                data['id'] = all_data[0]
                if (all_data[2].time()).strftime("%p") == "PM":
                    data['checkout'] = all_data[2]
                else:
                    data['checkin'] = all_data[2]
                data['date'] = all_data[1]
                result.append(data)
        if id:
            result_id = []
            for item in result:
                if item['id'] == id:
                    result_id.append(item)
            context = {
                'result': result_id
            }
        else:
            context = {
                'result': result
            }

        return render(request, 'attendanceRecord/attendance.html', context)
    return render(request, 'attendanceRecord/attendance.html')


def joinLetter(request):
    return render(request, 'joiningLetter/join.html')


def convertPdf(request):
    if request.method == "POST":
        this_folder = os.path.dirname(os.path.abspath(__file__))
        context = {
            'emp_name': request.POST['emp_name'],
            'date': request.POST['date'],
            'position': request.POST['position'],
            'location': request.POST['location'],
            'pre_company': request.POST['pre_company'],
            'guardian': request.POST['guardian'],
            'image_path':  'file://' + os.path.join(this_folder, 'static', 'images', 'webkrone.png')
        }
        html = render_to_string('joiningLetter/pdf_change.html', context)
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'inline:filename= "{}.pdf"'.format(
            "name")
        weasyprint.HTML(string=html).write_pdf(response, stylesheets=[
            CSS(string='body { font-size: 13px }')])
        return response


def zoomMeeting(request):
    """
        Created Zoom meeting by Hr users only.
    """
    if request.method == "POST":
        topic = request.POST.get('topic', False)

adminDashboardApp/templates/Employee/create_user.html
{% extends 'dashboard/index.html' %}{% load widget_tweaks %}
&nbsp;&nbsp;&nbsp;{% block contentbody %}

<form action="" method="post">
  {% csrf_token %}
  <p>Please, sign up using the following form:</p>
  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Username
  </label>

  <div class="input-group mb-3">
    {{user_form.username|add_class:"form-control" }}
  </div>
  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 20px 0 0;
      display: inline-block;
    "
  >
    Email
  </label>
  <div class="input-group mb-3">
    {{ user_form.email|add_class:"form-control" }}
  </div>

  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Password
  </label>

  <div class="input-group mb-3">
    {{user_form.password|add_class:"form-control"}}
  </div>
  <button class="btn btn-outline-success ml-4 mt-4" type="submit">
    Create my account
  </button>
</form>
{% endblock %}

adminDashboardApp/templates/Employee/delete_user.html
{% extends 'dashboard/index.html' %} {% block contentbody %}

<div class="container pt-5 text-center">
  <form method="post" novalidate action="">
    {% csrf_token %}
    <div class="col-sm-5">
      <h5><p>Are you sure you want to delete this user?</p></h5>

      <button type="submit" class="ml-5 btn btn-outline-success float-left">
        Submit
      </button>
      <a
        href="{% url 'adminDjango:deactivatedUsers' %}"
        class="me-5 btn btn-outline-danger float-right"
        >Cancel</a
      >
    </div>
  </form>
</div>
{% endblock %}

adminDashboardApp/templates/Employee/display_user.html
{% extends 'dashboard/index.html' %} {% load widget_tweaks %}
&nbsp;&nbsp;&nbsp;{% block contentbody %} {% if not admin %}
<a
  href="{% url 'adminDashboardApp:createNewUser' %}"
  class="btn btn-outline-success"
  style="float: right"
  >Create new User</a
>

{% endif %}
<br /><br />
<table class="table table-info table-striped text-center table-hover">
  <thead class="table-danger">
    <tr>
      <th scope="col">Sl No</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Contact Number</th>
      <th scope="col">Age</th>
      <th scope="col">Gender</th>
      <th scope="col">Address</th>
      {% if user.is_staff %}
      <th scope="col">Action</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for employee in employees %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{employee.user.first_name}}</td>
      <td>{{employee.user.email}}</td>
      <td>{{employee.contact_number}}</td>
      <td>{{employee.age}}</td>
      <td>{{employee.gender}}</td>
      <td>{{employee.address}}</td>
      {% if user.is_staff %}
      <td>
        {% if employee.user.is_active %} {% if employee.user.is_staff %}<a
          href="{% url 'adminDjango:convertToNormal' pk=employee.user.id %}"
          class="btn btn-outline-primary"
          >Normal</a
        >{% else %}<a
          href="{% url 'adminDjango:convertToAdmin' pk=employee.user.id %}"
          class="btn btn-outline-primary"
          >Admin</a
        >
        {% endif %}
        <a
          href="{% url 'adminDjango:deleteUser' pk=employee.user.id nm='deactivate' %}"
          class="btn btn-outline-danger"
          >Deactivate</a
        >

        {% else %}

        <a
          href="{% url 'adminDjango:activatedUsers' pk=employee.user.id %}"
          class="btn btn-outline-primary"
          >Activate</a
        >
        <a
          href="{% url 'adminDjango:deleteDeactivatedUser' pk=employee.user.id %}"
          class="ms-1 btn btn-outline-danger"
          >Delete</a
        >
        {% endif %}
      </td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

adminDashboardApp/templates/Employee/personal_detail.html
{% extends 'dashboard/index.html' %} {% load widget_tweaks %}
&nbsp;&nbsp;&nbsp;{% block contentbody %}

<form action="" method="post">
  {% csrf_token %}
  <p>Please, Enter your personal details</p>
  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    First Name
  </label>

  <div class="input-group mb-3">
    {{personal_form.first_name|add_class:"form-control" }}
  </div>
  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Last Name
  </label>

  <div class="input-group mb-3">
    {{personal_form.last_name|add_class:"form-control" }}
  </div>
  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 20px 0 0;
      display: inline-block;
    "
  >
    Age
  </label>
  <div class="input-group mb-3">
    {{ personal_form.age|add_class:"form-control" }}
  </div>

  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Address
  </label>

  <div class="input-group mb-3">
    {{personal_form.address|add_class:"form-control"}}
  </div>
  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Contact Number
  </label>

  <div class="input-group mb-3">
    {{personal_form.contact_number|add_class:"form-control"}}
  </div>
  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Gender
  </label>

  <div class="input-group mb-3">
    {{personal_form.gender|add_class:"form-control"}}
  </div>
  <button class="btn btn-outline-success ml-4 mt-4" type="submit">
    Summit
  </button>
</form>

{% endblock %}