accountUser/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
# from django.urls import include, url

app_name = "accountUser"
urlpatterns = [
    path('login/', LoginView.as_view(template_name='registration/signin.html'), name="signin"),
    path('logout/', LogoutView.as_view(template_name='registration/signout.html'), name="logout"),

]

adminDashboardApp/urls.py
from django.urls import path
from adminDashboardApp import views

app_name = 'adminDashboardApp'

urlpatterns = [
    path('', views.adminDashboard, name="dashboard"),
    path('pdf/', views.test, name="test"),
    path('createNewUser/', views.employeeRegisterUser, name='createNewUser'),
    path('employeePersonal/<int:pk>/', views.employeePersonalDetail,
         name='employeePersonalDetail'),
    path('listEmployee/', views.employeeDetailList, name="employee_list"),
    path('listAdmin/', views.adminDetailList, name="admin_list"),
    path('createRole/',
         views.createRoleAdmin.as_view(), name="createRole"),
    path('roleUpdate/<slug:slug>',
         views.roleUpdateView.as_view(), name="roleUpdate"),
    path('deleteRole/<slug:slug>',
         views.deleteAdminUserRoles.as_view(), name="deleteRole"),
    path('convertToAdmin/<int:pk>',
         views.convertNormalUserToAdmin, name="convertToAdmin"),
    path('convertToNormal/<int:pk>',
         views.convertAdminToNormal, name="convertToNormal"),
    path('deleteUser/<int:pk>/<str:nm>',
         views.deactivatedUserByAdmin, name="deleteUser"),
    path('deactivatedUsers/',
         views.deactivatedUsers, name="deactivatedUsers"),
    path('activatedUsers/<int:pk>',
         views.activatedUsers, name="activatedUsers"),
    path('deleteDeactivatedUser/<int:pk>',
         views.deleteDeactivatedUser.as_view(), name="deleteDeactivatedUser"),
    #path('attendance/', views.AttendanceRecord.as_view(), name="attendance"),
    path('attendance/', views.attendance, name="attendance"),
    path('joinLetter/', views.joinLetter, name="joinLetter"),
    path('converted_pdf/', views.convertPdf, name='converted_pdf'),

    path('zoom_meeting/', views.zoomMeeting, name='zoom_meeting'),
    path('zoom_meeting_create/', views.zoomMeetingCreateView.as_view(),
         name='zoom_meeting_create'),
    path('zoom_meeting_user_create/<int:pk>', views.zoomMeetingUsersCreateView.as_view(),
         name='zoom_meeting_user_create'),
    path('zoom_meeting_list/', views.zoomMeetingListView.as_view(),
         name='zoom_meeting_list'),
    path('zoom_meeting_user_details/<int:pk>', views.zoomMeetingDetailView.as_view(),
         name='zoom_meeting_user_detail'),
    path('zoom_meeting_Delete/<int:pk>', views.zoomMeetingDeleteView.as_view(),
         name='zoom_meeting_Delete'),
    path('zoom_meeting_send_mail/<int:pk>', views.zoomMeetingSendMailView.as_view(),
         name='zoom_meeting_send_mail'),
    path('organisation/', views.organisationView.as_view(),
         name='organisation_detail'),

    path('department/', views.departmentListView.as_view(),
         name="department"),
    path('departmentcreate/', views.departmentCreateView.as_view(),
         name="department_create"),
    path('departmentupdate/<int:pk>', views.departmentUpdateView.as_view(),
         name="department_update"),
    path('departmentdelete/<int:pk>', views.departmentDeleteView.as_view(),
         name="department_delete"),
]

adminDashboardPro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminDashboardApp.urls', namespace='adminDjango')),
    path('accounts/', include('accountUser.urls', namespace='account')),
    path('jobs/', include('jobPortalApp.urls', namespace='jobs')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

adminDashboardApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.utils import timezone
from django.contrib.auth.models import Permission
from django.utils.crypto import get_random_string


class EmployeeProfile(models.Model):
    GENDER = (
        ('Male', 'male'),
        ('Female', 'female')
    )
    age = models.IntegerField()
    gender = models.CharField(max_length=50, choices=GENDER, default='male')
    address = models.CharField(max_length=250)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user')
    contact_number = models.BigIntegerField()

    def __str__(self):
        return self.user.first_name


class Company(models.Model):
    company_name = models.CharField(max_length=255)
    company_apartment_num = models.CharField(max_length=255, null=True)
    company_street = models.CharField(max_length=255, null=True)
    company_city = models.CharField(max_length=255, null=True)
    company_state = models.CharField(max_length=255, null=True)
    company_country = models.CharField(max_length=255, null=True)
    company_contact_number = models.BigIntegerField()
    company_email_address = models.EmailField(max_length=255, null=True)

    def __str__(self):
        return self.company_name


class Department(models.Model):
    department_choices = (
        ('hr', 'Hr'),
        ('backoffice', 'Backoffice'),
        ('developer', 'Developer'),
        ('designer', 'Designer'),
        ('business_development', 'Business_Development'),
        ('admin', 'Admin')

    )
    department_name = models.CharField(
        max_length=250, choices=department_choices, default='hr')
    employee = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='employee')
    company = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name='company')

    def __str__(self):
        return self.department_name


class Attendance(models.Model):
    employee = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='employeeAttendance')
    date_time = models.DateTimeField(default=timezone.now, null=True)

    def __str__(self):
        return self.employee.first_name


class Role(models.Model):
    role_name = models.CharField(max_length=250)

    def __str__(self):
        return self.role_name


class EmployeeRole(models.Model):
    emp_role = models.ForeignKey(
        Role, on_delete=models.CASCADE, related_name='empRole')
    emp_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='empUser')

    def __str__(self):
        return self.employee.first_name


class AdminUserRoles(models.Model):
    id = models.AutoField(primary_key=True)
    slug = models.SlugField(max_length=500)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="admin_user_role")
    roles = models.ForeignKey(
        Permission, on_delete=models.CASCADE, null=True, related_name='roles')

    def __str__(self):
        return self.slug

    def save(self, *args, **kwargs):
        the_slug = get_random_string(10, '012345675765676789')
        self.slug = slugify(self.user.username + the_slug)
        super(AdminUserRoles, self).save(*args, **kwargs)


class ZoomMeetings(models.Model):
    meeting_topic = models.CharField(max_length=255)
    meeting_date = models.DateField()
    meeting_time = models.TimeField()
    meeting_duration = models.CharField(max_length=100)
    meeting_zoom_link = models.CharField(max_length=600, null=True)
    meeting_zoom_password = models.CharField(max_length=255, null=True)


class ZoomMeetingsUsers(models.Model):
    status_choice = (
        ('complete', 'Completed'),
        ('pending', 'Pending'),
        ('cancel', 'Canceled')
    )
    zoom_meeting = models.ForeignKey(ZoomMeetings, on_delete=models.CASCADE)
    users = models.CharField(max_length=555, null=True)
    users_staff = models.CharField(max_length=555, null=True)
    status = models.CharField(
        max_length=250, choices=status_choice, default='pending')
    mail_send = models.BooleanField(default=False)
    message = models.CharField(max_length=355, null=True)

adminDashboardApp/forms.py
from django import forms
from django.contrib.auth.models import User
from adminDashboardApp.models import EmployeeProfile, AdminUserRoles, Department, ZoomMeetings, ZoomMeetingsUsers


class UserForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'email']


class EmployeePersonalDetailForm(forms.ModelForm):
    first_name = forms.CharField(label="First Name", widget=forms.TextInput)
    last_name = forms.CharField(label="Last Name", widget=forms.TextInput)

    class Meta:
        model = EmployeeProfile
        fields = ['first_name', 'last_name', 'age',
                  'address', 'contact_number', 'gender']


class AdminUserRolesForm(forms.ModelForm):
    class Meta:
        model = AdminUserRoles
        fields = ['user', 'roles']


class AttendanceDetailForm(forms.Form):
    file_name = forms.FileField(
        label="Upload the files", widget=forms.FileInput)
    emp_id = forms.CharField(
        label="Enter Employee's ID", widget=forms.TextInput)
    fields = ['file_name', 'emp_id']


class EmployeeDepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['company', 'department_name', 'employee']


class ZoomMeetingsForm(forms.ModelForm):
    class Meta:
        model = ZoomMeetings
        fields = ['meeting_topic', 'meeting_date',
                  'meeting_time', 'meeting_duration']


class ZoomMeetingsUsersForm(forms.ModelForm):
    class Meta:
        model = ZoomMeetingsUsers
        fields = ['zoom_meeting', 'users', 'users_staff']


class ZoomMeetingsSendMailForm(forms.ModelForm):
    class Meta:
        model = ZoomMeetingsUsers
        fields = ['message']

adminDashboardApp/templates/Zoom/zoom.html
{% extends 'dashboard/index.html' %}{% load widget_tweaks %}
&nbsp;&nbsp;&nbsp;{% block contentbody %}

<div class="container">
    <div class="row">
        <h3 class="text-primary mb-3">Create a Zoom Meeting Here</h3>
            
           <img src="https://www.gosbcta.com/wp-content/uploads/2020/04/zoom-logo.jpg" class="img-fluid  " style="height: 540px;
  width: 100%;"alt="Image not found">
        
    </div>
</div>
<hr>
<div class="row container mb-2">

 {% if user_department %}
    <div class="col-sm-6">
    <a href="{% url 'adminDjango:zoom_meeting_create' %}" class="btn btn-outline-primary form-control">Create Meeting</a>
    </div>
 {% endif %}
   <div class="col-sm-6">
    <a href="{% url 'adminDjango:zoom_meeting_list' %}" class="btn btn-outline-primary form-control">List Meetings</a>
    </div>
    
</div>
{% endblock %}

adminDashboardApp/templates/Zoom/zoom_meeting_create.html
{% extends 'dashboard/index.html' %}{% load widget_tweaks %}
{% block contentbody %}

<div class="container ms-4 mt-2">
<form method="post" enctype="multipart/form-data">
 <h4 class="mb-3 text-primary"> Create Zoom Meeting link </h4>
  <img src="https://www.gosbcta.com/wp-content/uploads/2020/04/zoom-logo.jpg" class="img-fluid  " style="height: 440px;
  width: 90%;"alt="Image not found">
  {% csrf_token %}
   <div class="row container-fluid ms-4">
   <div class="col-sm-1"></div>
   <div class="col-sm-8 ">
  {% for field in form.visible_fields %}
  
    <label for="{{ field.id_for_label }}" class="mt-3 mb-1">{{ field.label }}</label>
    {% render_field field class="form-control" placeholder=field.label %}
    {% for error in field.errors %}
      <span class="help-block">{{ error }}</span>
    {% endfor %}
    
 {% endfor %}
  <button type="submit" class="btn btn-outline-primary mt-4 mb-2 me-4 float-start">Submit</button>
  <a class="btn btn-outline-danger mt-4 mb-2 float-end" href="{% url 'adminDjango:zoom_meeting' %}">CANCEL</a>
 </div>
 </div>
   
  </form>
</div>
{% endblock %}

adminDashboardApp/templates/Zoom/zoom_meeting_delete.html
{% extends 'dashboard/index.html' %} {% load widget_tweaks %}
&nbsp;&nbsp;&nbsp;{% block contentbody %}

<div class="container pt-5 text-centre">
  <form method="post" novalidate action="">
    {% csrf_token %}
    <div class="col-sm-4">
      <h5><p>Are you sure you want to remove user from this department.</p></h5>
      <button type="submit" class="btn btn-outline-success float-start">
        Submit
      </button>
      <a
        href="{% url 'adminDjango:zoom_meeting_list' %}"
        class="me-5 btn btn-outline-primary float-end"
        >Cancel</a
      >
    </div>
  </form>
</div>

{% endblock %}

adminDashboardApp/templates/Zoom/zoom_meeting_list.html
{% extends 'dashboard/index.html' %}{% load widget_tweaks %}
{% block style %}
<style>
      h3{
      text-transform: capitalize;
      }
      .badge{
      position: absolute;
      right: 0px;
      top: 0px;
      padding: 12px 15px;
      border-radius: 0 0 0 26px;
      font-size: 14px;
      }
      .card{
      border:0px;
      height: 100%;
      }
      .card-title{
      font-weight: bold;
      }
      </style>


{% endblock %}
&nbsp;&nbsp;&nbsp;{% block contentbody %}

<div class="container  mt-5 mb-5">
        <h2 class="mb-5 mt-2 text-primary"> Meeting Details </h2>
      
        <div class="row m-0">
          {% for meeting in zoommeetings_list %}
            <div class="col-sm-4 mb-4">
              <div class="card">
                <div class="card-body">
                  <span class="badge bg-warning">{{ forloop.counter }}</span>
                  <h3 class="card-title text-primary">{{meeting.meeting_topic}}</h3>
                  <h6 class="card-subtitle mb-2 text-muted">Markup Language</h6>
                  <p class="card-text">The HyperText Markup Language, or HTML is the standard markup language for documents.</p>
                  <a class="btn btn-outline-primary" href="{% url 'adminDjango:zoom_meeting_user_detail' pk=meeting.id %}">Details</a>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>


{% endblock %}

adminDashboardApp/templates/Zoom/zoom_meeting_send_mail.html
{% extends 'dashboard/index.html' %}{% load widget_tweaks %}
{% block contentbody %}

<div class="container ms-4 mt-5">
<form method="post" enctype="multipart/form-data">
 <h4> Enter user with department </h4>
  {% csrf_token %}
   <div class="row container">
   <div class="col-sm-6 ">
    {{form.as_p}}
  <button type="submit" class="btn btn-outline-primary mt-4 mb-2 me-4 float-start">Submit</button>
  <a class="btn btn-outline-danger mt-4 mb-2 float-end" href="{% url 'adminDjango:zoom_meeting_list' %}">CANCEL</a>
 </div>
 </div>
   
  </form>
</div>
{% endblock %}

adminDashboardApp/templates/Zoom/zoom_meeting_user_create.html
{% extends 'dashboard/index.html' %}{% load widget_tweaks %}
{% block contentbody %}

<div class="container ms-4 mt-5">
<form method="post" enctype="multipart/form-data">
 <h4> Enter users with zoom meeting </h4>
  {% csrf_token %}
   <div class="row container">
   <div class="col-sm-6 ">
  {% for field in form.visible_fields %}
 
    {% if field.label == 'Zoom meeting' %}
      <label for="{{ field.id_for_label }}" class="mt-3 mb-1">{{ field.label }}</label>
      <input value="{{zoom_meeting.meeting_topic}}" class="form-control" />
      <input value="{{zoom_meeting.id}}" name="zoom_meeting" class="form-control" style="display:None" />
    {% else %} 
    <label for="{{ field.id_for_label }}" class="mt-3 mb-1">{{ field.label }}</label>
    {% render_field field class="form-control" placeholder=field.label %}
    {% for error in field.errors %}
      <span class="help-block">{{ error }}</span>
    {% endfor %}
    {% endif %}
 {% endfor %}
  <button type="submit" class="btn btn-outline-primary mt-4 mb-2 me-4 float-start">Submit</button>
  <a class="btn btn-outline-danger mt-4 mb-2 float-end" href="{% url 'adminDjango:department' %}">CANCEL</a>
 </div>
 </div>
   
  </form>
</div>
{% endblock %}

adminDashboardApp/templates/Zoom/zoom_meeting_user_deatil.html
{% extends 'dashboard/index.html' %}{% load widget_tweaks %}
&nbsp;&nbsp;&nbsp;{% block contentbody %}
<div class="container">
 <h4 class="mb-3 mt-2 text-primary">  {% if zoom_meeting_users %} {{zoom_meeting_users.zoom_meeting.meeting_topic}} {% else %} {{zoom_meeting.meeting_topic}} {% endif %} Meeting</h4>
  
  <img src="https://img.freepik.com/free-vector/business-office-people-maintain-social-distancing-office-room-stop-covid19-coronavirus_40876-2452.jpg?w=1480&t=st=1659344420~exp=1659345020~hmac=d8fcfb839a06db55997910b9440ba7e24121fec9000877bac07405fa61bcedd6" class="w-100 " style="height: 440px;
        width: 90%;"alt="Image not found">
  
  <hr>
  
   {% if zoom_meeting_users %}
       {% if user_department %}
       
          {% if not zoom_meeting_users.mail_send %}
          <div class="col-sm-6">
        
       <a class="btn btn-outline-primary mt-5 form-control" href="{% url 'adminDjango:zoom_meeting_send_mail' pk=zoom_meeting_users.id %}"> Send to the users of zoom interview link </a>
       </div>
       {% endif %}
    
        <div class="col-sm-5">    
       <a class="btn btn-outline-primary mt-5 form-control" href="{% url 'adminDjango:zoom_meeting_Delete' pk=zoom_meeting_users.zoom_meeting.id %}"> Delete zoom meeting </a>
        </div>
       {% endif %}
    
     
       

       <div class = "row container-fluid">
        
         <div class="col-sm-4">
         <hr class="mt-3">
            <div class=""><span class="h5 mt-2 bg-primary rounded-pill text-light form-control ">Meeting Date :
                        <a class=" text-light text-decoration-none">{{zoom_meeting_users.zoom_meeting.meeting_date}}</a></span> </div>
            <div class="mt-3">
                <span class="h5 bg-warning rounded-pill text-light form-control">Meeting Time :
                    <a class=" text-light text-decoration-none">{{zoom_meeting_users.zoom_meeting.meeting_time}}</a></span></div>
                    <div class="mt-3"><span class="h5 bg-primary form-control rounded-pill text-light">Meeting Duration :
                        <a class=" text-decoration-none text-light ">{{zoom_meeting_users.zoom_meeting.meeting_duration}} minuts</a></span> </div>
                        <div class="mt-3"><span class="h5 bg-warning form-control rounded-pill text-light">Meeting Status :
                            <a class=" text-light text-decoration-none">{{zoom_meeting_users.status}}</a></span> </div>
                            
                                       
               </div>
            <div class="col-sm-7">
            <hr class="mt-3">
             <div class="mt-2"><span class="bg-primary form-control rounded-pill text-light"> Topic:
                                            <a class=" text-light text-decoration-none"></a>{{zoom_meeting_users.zoom_meeting.meeting_topic}}</span> </div>
              <div class="mt-3">
                  <span class="h5 bg-warning rounded-pill text-light form-control">Users :
                      <a class=" text-light text-decoration-none">{{zoom_meeting_users.users}}</a></span></div>
                      <div class="mt-3"><span class="h5 bg-primary form-control rounded-pill text-light">Users staff :
                          <a class=" text-light text-decoration-none">{{zoom_meeting_users.users_staff}}</a></span>
                        </div>
            <div>
       </div>
      </div>
      
       <div class = "row mt-4">
         
            <span class="h5 bg-danger form-control rounded-pill text-light">Meeting Zoom Link :<a class=" text-light text-decoration-none"href ="{{zoom_meeting_users.zoom_meeting.meeting_zoom_link}}"> {{zoom_meeting_users.zoom_meeting.meeting_zoom_link}}  </a></span>
       </div>
    {% else %}
        {% if user_department %}
        <div class="row ">
          <div class = "col-sm-6">
           <a class="btn btn-outline-primary form-control" href="{% url 'adminDjango:zoom_meeting_user_create' pk=zoom_meeting.id %}">Add users for scheduling interview with exist zoom meeting links</a>
          </div>

             <div class = "col-sm-5">
              <a class="btn btn-outline-primary form-control" href="{% url 'adminDjango:zoom_meeting_Delete' pk=zoom_meeting.id %}"> Delete zoom meeting </a>
          </div>
        </div>
       {% endif %}
         <div class = "row container-fluid">
        
         <div class="col-sm-4">
         <hr class="mt-3">
          <p><span class="h5 ms-4">Meeting Date : </span> {{zoom_meeting.meeting_date}}</p>
            <p><span class="h5 ms-4">Meeting Time : </span> {{zoom_meeting.meeting_time}}</p>
            <p><span class="h5 ms-4">Meeting Duration : </span> {{zoom_meeting.meeting_duration}} minuts</p>
             
                       
            </div>
            <div class="col-sm-7">
            <hr class="mt-3">
           <p><span class="h4 ms-4">Topic : </span> {{zoom_meeting.meeting_topic}}</p>
              
            <div>
       </div>
       </div>
      
         <div class = "row mt-4">
         
            <p><span class="h5 ms-4">Meeting Zoom Link : </span><a href ="{{zoom_meeting.meeting_zoom_link}}"> {{zoom_meeting.meeting_zoom_link}}  </a></p>
         
         </div>

     {% endif %}
      
    
</div>
{% endblock %}