accountUser/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
# from django.urls import include, url

app_name = "accountUser"
urlpatterns = [
    path('login/', LoginView.as_view(template_name='registration/signin.html'), name="signin"),
    path('logout/', LogoutView.as_view(template_name='registration/signout.html'), name="logout"),

]

adminDashboardPro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminDashboardApp.urls', namespace='adminDjango')),
    path('accounts/', include('accountUser.urls', namespace='account')),
    path('jobs/', include('jobPortalApp.urls', namespace='jobs')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

jobPortalApp/urls.py
from django.urls import path
from . import views

app_name = 'jobPortalApp'

urlpatterns = [
    path('', views.homejob, name="homejob"),
    path('userjobsprofile/', views.jobUserProfileListView.as_view(),
         name="user_job_profile"),
    path('userprofilejobcreate', views.jobUserProfileCreateView.as_view(),
         name="user_profile_job_create"),
    path('userprofilejobupdate/<slug:slug>', views.jobUserProfileUpdateView.as_view(),
         name="user_profile_job_update"),
    path('userjobsprofiledelete/<slug:slug>/', views.jobUserProfileDeleteView.as_view(),
         name="user_job_profile_delete"),
    path('userjobskillcreate', views.jobUserSkillCreateView.as_view(),
         name="user_skill_job_create"),
    path('userjobskilldelete/<slug:slug>/', views.jobUserSkillDeleteView.as_view(),
         name="user_skill_job_delete"),
    path('jobcreate', views.jobCreateView.as_view(),
         name="job_create"),
    path('joblist/', views.jobListView.as_view(),
         name="job_list"),
    path('jobupdate/<slug:slug>', views.jobUpdateView.as_view(),
         name="job_update"),
    path('jobdelete/<slug:slug>/', views.jobDeleteView.as_view(),
         name="job_delete"),
    path('jobapply/<slug:slug>', views.jobAppliedCreateView,
         name="job_apply"),
    path('jobappliedusers/<slug:slug>', views.jobAppliedUsersListView.as_view(),
         name="job_applied_users"),
    path('jobsapplieduser/', views.jobAppliedByUserListView.as_view(),
         name="job_applied_by_user"),
]

jobPortalApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.utils import timezone
from django.utils.crypto import get_random_string
from adminDashboardApp.models import Company
# Create your models here.

CHOICES = (
    ('Full Time', 'Full Time'),
    ('Part Time', 'Part Time'),
    ('Internship', 'Internship'),
    ('Remote', 'Remote'),
)


class JobUsersProfile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='job_profile')
    id = models.AutoField(primary_key=True)
    resume = models.FileField(upload_to='resumes', null=True, blank=True)
    slug = models.SlugField(max_length=500)
    higer_secondary_year = models.IntegerField(blank=True)
    secondary_year = models.IntegerField(blank=True)
    grad_year = models.IntegerField(blank=True)
    post_grad_year = models.IntegerField(blank=True)
    looking_for = models.CharField(
        max_length=30, choices=CHOICES, default='Full Time', null=True)

    def save(self, *args, **kwargs):
        the_slug = get_random_string(10, '012345675765676789')
        self.slug = slugify(self.user.username + the_slug)
        super(JobUsersProfile, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.username


class Skill(models.Model):
    id = models.AutoField(primary_key=True)
    slug = models.SlugField(max_length=500)
    skill = models.CharField(max_length=200)
    user = models.ForeignKey(
        User, related_name='skills', on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        the_slug = get_random_string(10, '012345675765676789')
        self.slug = slugify(self.user.username + the_slug)
        super(Skill, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.username


class AddressDetails(models.Model):
    id = models.AutoField(primary_key=True)
    slug = models.SlugField(max_length=500)
    street = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=255, null=True)
    state = models.CharField(max_length=255, null=True)
    country = models.CharField(max_length=255, null=True)
    pincode = models.CharField(max_length=255, null=True)

    def save(self, *args, **kwargs):
        the_slug = get_random_string(10, '012345675765676789')
        self.slug = slugify(self.street + the_slug)
        super(AddressDetails, self).save(*args, **kwargs)

    def __str__(self):
        return self.city


class JobDetails(models.Model):
    id = models.AutoField(primary_key=True)
    slug = models.SlugField(max_length=500)
    company = models.ForeignKey(
        Company, related_name='Company_job', on_delete=models.CASCADE)
    job_title = models.CharField(max_length=255, null=True)
    job_description = models.CharField(max_length=600, null=True)
    experiance = models.CharField(max_length=255, null=True)
    salary = models.CharField(max_length=255, null=True)
    address = models.ForeignKey(AddressDetails, on_delete=models.CASCADE)
    hiring_members = models.BigIntegerField()
    industry_type = models.CharField(max_length=255, null=True)
    employement_type = models.CharField(
        max_length=30, choices=CHOICES, default='Full Time', null=True)
    qualification = models.CharField(max_length=255, null=True)

    def save(self, *args, **kwargs):
        the_slug = get_random_string(10, '012345675765676789')
        self.slug = slugify(self.job_title + the_slug)
        super(JobDetails, self).save(*args, **kwargs)

    def __str__(self):
        return self.job_title


class AppliedJobs(models.Model):
    CHOICE = (
        ('Pending', 'Pending'),
        ('Completed', 'Completed'),
    )
    job = models.ForeignKey(
        JobDetails, related_name='applied_job', on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, related_name='applied_user', on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    status = models.CharField(
        max_length=30, choices=CHOICE, default='Pending', null=True)

    def __str__(self):
        return self.job.job_title

jobPortalApp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import JobUsersProfile, Skill, JobDetails, AddressDetails, AppliedJobs


class JobUsersProfileForm(forms.ModelForm):
    class Meta:
        model = JobUsersProfile
        fields = ['secondary_year', 'higer_secondary_year',
                  'grad_year', 'post_grad_year', 'looking_for', 'resume']


class UserSkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = ['skill']


class JobDetailsForm(forms.ModelForm):
    class Meta:
        model = JobDetails
        fields = ['company', 'job_title', 'job_description', 'experiance', 'salary',
                  'hiring_members', 'industry_type', 'employement_type', 'qualification']

jobPortalApp/views.py
from multiprocessing import get_context
from django.shortcuts import render, redirect
from django.views.generic import UpdateView, CreateView, ListView, DetailView, DeleteView
from django.contrib.auth.models import User
from .models import JobDetails, JobUsersProfile, Skill, AddressDetails, AppliedJobs
from .forms import JobUsersProfileForm, UserSkillForm, JobDetailsForm
from adminDashboardApp.models import Department
# Create your views here.


def homejob(request):
    pass


class jobUserProfileListView(ListView):
    """
        User can show the details of job profile.
    """
    model = JobUsersProfile
    #template_name = 'jobs/job_profile_job_list.html'
    template_name = 'jobs/job.html'
    context_object_name = "jobuserprofile"

    def get_queryset(self):
        # original qs
        qs = super().get_queryset()
        # filter by a variable captured from url, for example
        context = {}
        context['user_job_profile'] = qs.filter(
            user__username=self.request.user.username)
        if context['user_job_profile']:
            context['user_job_profile'] = context['user_job_profile'][0]

        context['skill'] = Skill.objects.filter(
            user__username=self.request.user.username)
        user_department = Department.objects.filter(
            employee__username=self.request.user.username, department_name='hr')
        if user_department:
            context['user_department'] = user_department[0].employee.username
        else:
            context['user_department'] = None
        print(context['user_department'])
        return context


class jobUserProfileCreateView(CreateView):
    """
        User can add the profile for getting jobs.
    """
    form_class = JobUsersProfileForm
    template_name = 'jobs/create_user_profile_job.html'

    def form_valid(self, form):
        data = form.save(commit=False)
        user = User.objects.get(id=self.request.user.id)
        data.user = user
        data.save()
        return redirect('jobs:user_skill_job_create')


class jobUserProfileUpdateView(UpdateView):
    """
        User can edit the profile for getting jobs.
    """
    model = JobUsersProfile
    form_class = JobUsersProfileForm
    success_url = '/jobs/userjobsprofile/'
    template_name = 'jobs/update_user_job_profile.html'

    def get_form_kwargs(self):
        kwargs = super(jobUserProfileUpdateView, self).get_form_kwargs()
        kwargs.update()
        return kwargs


class jobUserProfileDeleteView(DeleteView):
    template_name = 'jobs/delete_user_job_profile.html'
    model = JobUsersProfile
    success_url = '/jobs/userjobsprofile/'


class jobUserSkillCreateView(CreateView):
    """
        User can add the Skills for getting jobs.
    """
    form_class = UserSkillForm
    template_name = 'jobs/user_skill_job_create.html'

    def form_valid(self, form):
        data = form.save(commit=False)
        user_name = User.objects.get(id=self.request.user.id)
        data.user = user_name
        data.save()
        return redirect('jobs:user_job_profile')


class jobUserSkillDeleteView(DeleteView):
    template_name = 'jobs/delete_user_skill.html'
    model = Skill
    success_url = '/jobs/userjobsprofile/'


class jobCreateView(CreateView):
    """
        Hrs can add the Job for company.
    """
    form_class = JobDetailsForm
    template_name = 'jobs/create_jobs.html'

    def form_valid(self, form):
        data = form.save(commit=False)
        street = self.request.POST['street']
        city = self.request.POST['city']
        state = self.request.POST['state']
        country = self.request.POST['country']
        pin_code = self.request.POST['pin_code']
        address = AddressDetails.objects.create(
            street=street, city=city, state=state, country=country, pincode=pin_code)
        data.address = address
        data.save()
        return redirect('jobs:user_job_profile')


class jobListView(ListView):
    """
        Display the all jobs for company.
    """
    model = JobDetails
    template_name = 'jobs/list_jobs.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        # original qs
        qs = super().get_queryset()
        # filter by a variable captured from url, for example
        context = {}
        context['job_list'] = qs
        user_department = Department.objects.filter(
            employee__username=self.request.user.username, department_name='hr')
        if user_department:
            context['user_department'] = user_department[0].employee.username
        else:
            context['user_department'] = None
        return context


class jobUpdateView(UpdateView):
    """
        Hrs can update the Job for company.
    """
    model = JobDetails
    form_class = JobDetailsForm
    success_url = '/jobs/joblist/'
    template_name = 'jobs/hrUsers/update_job.html'

    def get_form_kwargs(self):
        address = AddressDetails.objects.get(id=self.object.address.id)
        kwargs = super(jobUpdateView, self).get_form_kwargs()
        street = self.request.POST.get('street')
        city = self.request.POST.get('city')
        state = self.request.POST.get('state')
        country = self.request.POST.get('country')
        pin_code = self.request.POST.get('pin_code')
        if street:
            address.street = street
        if city:
            address.city = city
        if state:
            address.state = state
        if country:
            address.country = country
        if pin_code:
            address.pincode = pin_code
        address.save()
        kwargs.update()
        return kwargs


class jobDeleteView(DeleteView):
    """
        Hrs can delete the Job for company.
    """
    template_name = 'jobs/hrUsers/delete_job.html'
    model = JobDetails
    success_url = '/jobs/joblist/'


def jobAppliedCreateView(request, slug):
    try:
        user = User.objects.get(username=request.user.username)
    except:
        return redirect('account:signin')
    job = JobDetails.objects.get(slug=slug)
    data = AppliedJobs.objects.filter(user=user, job=job)

    if not data:
        data = AppliedJobs.objects.create(user=user, job=job)

    return redirect('jobs:job_list')


class jobAppliedUsersListView(ListView):
    model = AppliedJobs
    template_name = 'jobs/users/applied_users.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = AppliedJobs.objects.filter(
            job__slug=self.kwargs['slug'])
        print(context['users'])
        return context


class jobAppliedByUserListView(ListView):
    model = AppliedJobs
    template_name = 'jobs/users/applied_jobs_user.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = AppliedJobs.objects.filter(
            user__username=self.request.user.username)
        print(context['users'])
        return context

jobPortalApp/templates/jobs/create_jobs.html
{% extends 'dashboard/index.html' %}{% load widget_tweaks %}
&nbsp;&nbsp;&nbsp;{% block contentbody %}

<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <h4 class="text-center mt-2">Create job for Company </h4>
  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Company Name
  </label>

  <div class="input-group mb-3">
    {{form.company|add_class:"form-control" }}
  </div>
  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 20px 0 0;
      display: inline-block;
    "
  >
    Job Title
  </label>
  <div class="input-group mb-3">
    {{ form.job_title|add_class:"form-control" }}
  </div>

   <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 20px 0 0;
      display: inline-block;
    "
  >
    Industry Type
  </label>
  <div class="input-group mb-3">
    {{ form.industry_type|add_class:"form-control" }}
  </div>

   <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 20px 0 0;
      display: inline-block;
    "
  >
    Employement Type
  </label>
  <div class="input-group mb-3">
    {{ form.employement_type|add_class:"form-control" }}
  </div>



 <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 20px 0 0;
      display: inline-block;
    "
  >
    Qualification
  </label>
  <div class="input-group mb-3">
    {{ form.qualification|add_class:"form-control" }}
  </div>


  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Hiring Members
  </label>

  <div class="input-group mb-3">
    {{form.hiring_members|add_class:"form-control"}}
  </div>
   <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Experiance 
  </label>

  <div class="input-group mb-3">
    {{form.experiance|add_class:"form-control"}}
  </div>
   <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Salary 
  </label>

  <div class="input-group mb-3">
    {{form.salary|add_class:"form-control"}}
  </div>
   <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Job Descriptions 
  </label>

  <div class="input-group mb-3">
    {{form.job_description|add_class:"form-control"}}
  </div>

   <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Address 
  </label>
  <div class="row container">
  <div class="col-sm-6">
   <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Street 
  </label>

  <div class="input-group mb-3">
    <input type="text" name="street" class="form-control">
  </div>
  </div>
  <div class="col-sm-6">
  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    City 
  </label>

  <div class="input-group mb-3">
    <input type="text" name="city" class="form-control">
  </div>
  </div>
  <div class="col-sm-6">
  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    State 
  </label>

  <div class="input-group mb-3">
   <input type="text" name="state" class="form-control">
  </div>
  </div>
  <div class="col-sm-6">
  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Country 
  </label>

  <div class="input-group mb-3">
    <input type="text" name="country" class="form-control">
  </div>
  </div>
  <div class="col-sm-6">
  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Pin code 
  </label>

  <div class="input-group mb-3">
    <input type="text" name="pin_code" class="form-control">
  </div>
  </div>
  </div>
  <button class="btn btn-outline-success ml-4 mt-4" type="submit">
    Create job 
  </button>
</form>
{% endblock %}

jobPortalApp/templates/jobs/create_user_profile_job.html
{% extends 'dashboard/index.html' %}{% load widget_tweaks %}
&nbsp;&nbsp;&nbsp;{% block contentbody %}

<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <p>Create job profiles :</p>
  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Secondary Year
  </label>

  <div class="input-group mb-3">
    {{form.secondary_year|add_class:"form-control" }}
  </div>
  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 20px 0 0;
      display: inline-block;
    "
  >
    Higer Secondary Year
  </label>
  <div class="input-group mb-3">
    {{ form.higer_secondary_year|add_class:"form-control" }}
  </div>
   <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 20px 0 0;
      display: inline-block;
    "
  >
    Graduation Year
  </label>
  <div class="input-group mb-3">
    {{ form.grad_year|add_class:"form-control" }}
  </div>

 <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 20px 0 0;
      display: inline-block;
    "
  >
    Post Graduation Year
  </label>
  <div class="input-group mb-3">
    {{ form.post_grad_year|add_class:"form-control" }}
  </div>


  <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Looking For
  </label>

  <div class="input-group mb-3">
    {{form.looking_for|add_class:"form-control"}}
  </div>
   <label
    style="
      font-family: Source Sans Pro;
      font-weight: 600;
      font-size: 16px;
      margin: 30px 0 0;
      display: inline-block;
    "
  >
    Resume
  </label>

  <div class="input-group mb-3">
    {{form.resume|add_class:"form-control"}}
  </div>
  <button class="btn btn-outline-success ml-4 mt-4" type="submit">
    Create my job profile
  </button>
</form>
{% endblock %}

jobPortalApp/templates/jobs/job.html
{% extends 'dashboard/index.html' %} 
{% load static %}
{% block contentbody %}

<div class="container">

<img src="{% static 'images/jobs/job1.png' %}" class="w-100" style="height:450px"/>

</div>

 <div class="row container mt-2 ms-5">
 <div class="col-sm-5 mt-1 ms-3">
 <a class="text-decoration-none btn btn-outline-primary btn-lg w-100" href="{% url 'jobs:job_list' %}">
      Job Lists
  </a>
  </div>
   <div class="col-sm-5 mt-2 ms-3">
    {% for key, value in jobuserprofile.items %} 
     {% if key == 'user_job_profile' %}
        {% if value %}
  <a class="text-decoration-none btn btn-outline-primary btn-lg w-100" href="{% url 'jobs:user_profile_job_update' slug=value.slug %}">
      User Update Job Profile
  </a>
  {% else %}
     <a class="text-decoration-none btn btn-outline-primary btn-lg w-100" href="{% url 'jobs:user_profile_job_create' %}">
        User Add Job Profile
  </a>
  {% endif %}
    {% endif %}
    {% endfor %}
   </div>
   <div class="col-sm-5 mt-3 ms-3">
  <a class="text-decoration-none btn btn-outline-primary btn-lg w-100" href="{% url 'jobs:user_skill_job_create' %}">
     User Add Skills
 </a>
  </div>
  <div class="col-sm-5 mt-3 ms-3">
  <a class="text-decoration-none btn btn-outline-primary btn-lg w-100" href="">
  Job Profile
  </a>
  </div>
   <div class="col-sm-5 mt-3 ms-3">
  <a class="text-decoration-none btn btn-outline-primary btn-lg w-100" href="{% url 'jobs:job_applied_by_user' %}">
  Applied Company
  </a>
  </div>
  {% for key, value in jobuserprofile.items %} 

 {% if key == 'user_department' %}
        {% if value %}
       
   <div class="col-sm-5 mt-3 ms-3">
  <a class="text-decoration-none btn btn-outline-primary btn-lg w-100" href="{% url 'jobs:job_create' %}">
      Hrs Add Jobs
  </a>
  </div>
 {% endif %}
       
 {% endif %}
 {% endfor %}
</div>


  {% endblock %}

jobPortalApp/templates/jobs/job_profile_job_list.html
{% extends 'dashboard/index.html' %}{% load widget_tweaks %}
&nbsp;&nbsp;&nbsp;{% block contentbody %}

<div class="row container">
 <div class="col-sm-4">
{% if user_department %}
<a class="btn btn-outline-primary" href="{% url 'jobs:job_create' %}">Add Job</a>
{% endif %}
{{user_department}}
<a class="btn btn-outline-primary" href="{% url 'jobs:user_skill_job_create' %}">Add Skills</a>


</div>
<div class="col-sm-7">
<a class="btn btn-outline-primary" href="{% url 'jobs:user_profile_job_create' %}">Create Job Profile</a>
<a class="btn btn-outline-primary" href="{% url 'jobs:job_list' %}">List jobs</a>

</div>
</div>



<ul>
{% for key, value in jobuserprofile.items %} 

 {% if key == 'user_department' %}
        {% if value %}
        <a class="btn btn-outline-primary" href="{% url 'jobs:job_create' %}">Add Job</a>
        {% endif %}
       
 {% endif %}
  
  {% if key == 'user_job_profile' %}
  {% if value %}
  <div class="container">
  {{value.slug}}
  <li> User Details</li><span class="float-end"><a class="btn btn-outline-primary" href="{% url 'jobs:user_profile_job_update' slug=value.slug %}">Update Job Profile</a> <a class="btn btn-outline-primary" href="{% url 'jobs:user_job_profile_delete' slug=value.slug %}">Delete Job Profile</a></span>
   {{value.user}}<br>
   {{value.secondary_year}} <br>
   {{value.higer_secondary_year}}<br>
   {{value.grad_year}}<br>
   {{value.post_grad_year}}<br>
   {{value.resume}}<br>
   </div>
   {% endif %}
  {% endif %}
  {% if key == 'skill' %}
   {% if value %}
  <div class="container">
     <li> User Skills</li>
      {% for skil in value %}
        <span class="mt-2" > {{skil.skill}} <a class = "btn btn-outline-primary mt-2" href="{% url 'jobs:user_skill_job_delete' slug=skil.slug %}">Delete Skill</a> </span><br>
      {% endfor %}
      </div>
    {% endif %}
  {% endif %}
{% endfor %}
</ul>

{% endblock %}

jobPortalApp/templates/jobs/list_jobs.html
{% extends 'dashboard/index.html' %}{% load widget_tweaks %}
{% block style %}

{% endblock %}
&nbsp;&nbsp;&nbsp;{% block contentbody %}
<div class="row container mt-5 ms-5">
<h4 class="text-center mt-3"> Job List</h4>
</div>
<div class="container-fluid mt-5 ms-5">
<div class="row">
{% for key, value in jobs.items %} 
{% if key == 'job_list' %}
{% for job in value %}
 <div class="col-md-3">
            <div class="card p-2">
                <div class="text-right d-flex justify-content-between mt-3"> <small>{{job.employement_type}}</small><button class="btn btn-sm btn-outline-dark">Detail</button> </div>
                <div class="text-center mt-2 p-3"> <img src="https://img.icons8.com/officel/80/000000/dribbble.png" width="60" /> <span class="d-block font-weight-bold">{{job.job_title}}</span>
                    <hr> <span>{{job.company}}</span>
                    <div class="d-flex flex-row align-items-center justify-content-center"> <i class="fa fa-map-marker"></i> <small class="ml-1">{{job.address.street}} {{job.address.city}} {{job.address.state}} {{job.address.country}}</small> </div>
                    <div class="d-flex justify-content-between mt-3"> <span>${{job.salary}}</span>
                    {% for keys, values in jobs.items %} 
                      {% if keys == 'user_department' and values %}
                      </div>
                      <hr>
                      <div>
                      <a class="btn btn-sm btn-outline-dark me-1" href="{% url 'jobs:job_update' slug=job.slug %}">update</a><a class="btn btn-sm btn-outline-danger" href="{% url 'jobs:job_delete' slug=job.slug %}">delete</a>
                      <a class="btn btn-sm btn-outline-dark" href="{% url 'jobs:job_applied_users' slug=job.slug %}">Applied Users</a> 
                      {% elif keys == 'user_department' %}
                      <a class="btn btn-sm btn-outline-dark" href="{% url 'jobs:job_apply' slug=job.slug %}">Apply Now</a> 
                      {% endif %}
                    {% endfor %}
                     </div>
                </div>
            </div>
        </div>

    {% endfor %}
{% endif %}

{% endfor %}
</div>
</div>
{% endblock %}